version: '3'
services:
  tornStocks:
    container_name: imdbscrapper
    image: zebrajr/imdbscrapper:latest
    volumes:
    #- '${PWD}/src:/opt/imdbscrapper:ro'
    - './src/scrapper/:/opt/imdbscrapper:ro'
    user: 1000:1000
    environment:
      - removeDuplicates=1
      - START_URL=2000000
      - END_URL=0
      - STEPUPCYCLE=50
      - PROCESSES=5
    depends_on:
      - imdbdb


  imdbdb:
    container_name: imdbdb
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./storage/back/:/var/lib/mysql"


  phpmyadmin:
    container_name: imdbphpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: unless-stopped
    environment:
      PMA_HOST: imdbdb
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "1239:80"
