version: '3'
services:
  tornStocks:
    container_name: imdbscrapper
    image: zebrajr/imdbscrapper:latest
    volumes:
    - '${PWD}/src:/opt/imdbscrapper:ro'
    - '${PWD}/storage:/opt/storage'
    user: 1000:1000
